# Generated by Django 4.2.6 on 2023-10-24 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceComprobacion',
            fields=[
                ('idBalance', models.AutoField(primary_key=True, serialize=False)),
                ('fechaDeBalance', models.DateField()),
                ('saldoAcreedor', models.FloatField()),
                ('saldoDeudor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoCuenta',
            fields=[
                ('idCuenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5)),
                ('tipoDeCuenta', models.CharField(max_length=50)),
                ('nombreDeCuenta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idInventario', models.AutoField(primary_key=True, serialize=False)),
                ('fechaDeRegistroDeOperacion', models.DateField()),
                ('tipoDeOperacion', models.CharField(max_length=50)),
                ('cantidadProducto', models.IntegerField()),
                ('costoUnitario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTransaccion',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('fechaDeRegistro', models.DateField()),
                ('tipoDeMonto', models.CharField(max_length=50)),
                ('montoTransaccion', models.FloatField()),
                ('descripcion', models.TextField()),
                ('CatalogoCuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppGameZone.catalogocuenta')),
                ('balanceComprobacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppGameZone.balancecomprobacion')),
            ],
        ),
        migrations.AddField(
            model_name='balancecomprobacion',
            name='CatalogoCuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppGameZone.catalogocuenta'),
        ),
    ]
