# Generated by Django 4.2.6 on 2023-10-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGameZone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrotransaccion',
            old_name='CatalogoCuenta',
            new_name='registroCatalogo',
        ),
        migrations.AlterField(
            model_name='registrotransaccion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
