# Generated by Django 4.2.6 on 2023-10-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGameZone', '0004_alter_libromayor_saldoacreedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecontable',
            name='comprasNetas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cierrecontable',
            name='comprasTotales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cierrecontable',
            name='costoDeVentas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cierrecontable',
            name='mercanciasDisponibles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cierrecontable',
            name='ventasNetas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
