# Generated by Django 4.2.6 on 2023-10-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGameZone', '0006_rename_fechaderegistrodeoperacion_inventario_fechademovimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidadProducto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='costoUnitario',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
