# Generated by Django 4.2.6 on 2023-10-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGameZone", "0010_remove_cierrecontable_idvalorentrada_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventario",
            name="idValorEntrada",
        ),
        migrations.AddField(
            model_name="inventario",
            name="entradaResiduo",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
