# Generated by Django 4.2.6 on 2023-10-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppGameZone", "0011_remove_inventario_idvalorentrada_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventario",
            name="entradaResiduo",
        ),
    ]
