# Generated by Django 4.2.6 on 2023-10-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGameZone", "0012_remove_inventario_entradaresiduo"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventario",
            name="montoValor",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventario",
            name="saldoValor",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
