# Generated by Django 4.2.6 on 2023-11-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppGameZone", "0013_inventario_montovalor_inventario_saldovalor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Costeo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("materiaPrima", models.FloatField(blank=True, null=True)),
                ("costoMateriaPrima", models.FloatField(blank=True, null=True)),
                ("manoDeObra", models.FloatField(blank=True, null=True)),
                ("costoManoDeObra", models.FloatField(blank=True, null=True)),
                ("tasaCIF", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
