# Generated by Django 4.2.6 on 2023-10-26 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGameZone', '0002_rename_catalogocuenta_registrotransaccion_registrocatalogo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreContable',
            fields=[
                ('idCierre', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LibroMayor',
            fields=[
                ('idLibro', models.AutoField(primary_key=True, serialize=False)),
                ('nombreLibro', models.CharField(max_length=50)),
                ('fechaDeApertura', models.DateField()),
                ('fechaDeCierre', models.DateField()),
                ('saldoAcreedor', models.FloatField()),
                ('saldoDeudor', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='registrotransaccion',
            name='balanceComprobacion',
        ),
        migrations.AddField(
            model_name='inventario',
            name='descripcionInventario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BalanceComprobacion',
        ),
        migrations.AddField(
            model_name='cierrecontable',
            name='cierreLibro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppGameZone.libromayor'),
        ),
        migrations.AddField(
            model_name='registrotransaccion',
            name='registroLibro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppGameZone.libromayor'),
        ),
    ]
