# Generated by Django 4.2.6 on 2023-10-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGameZone', '0003_cierrecontable_libromayor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libromayor',
            name='saldoAcreedor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='saldoDeudor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
