# Generated by Django 4.2.6 on 2023-10-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGameZone', '0005_cierrecontable_comprasnetas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='fechaDeRegistroDeOperacion',
            new_name='fechaDeMovimiento',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='tipoDeOperacion',
            new_name='tipoDeMovimiento',
        ),
    ]
